export const theme = {
  colors: {
    bgBase: "#FDFCFB",
    bgDark: "#121212",
    bgSurface: "#FFFFFF",
    oliveMuted: "#5A5A40",
    oliveAccent: "#7C8B6D",
    charcoal: "#1A1A1A",
    richBlack: "#0D0D0D",
    glassBg: "rgba(255, 255, 255, 0.8)",
    glassBorder: "rgba(0, 0, 0, 0.05)",
    textMain: "#1A1A1A",
    textDim: "#707070",
    textWhite: "#FFFFFF",
    accentBlue: "#00A3FF",
    accentGreen: "#2ecc71",
    accentGold: "#D4AF37",
    accentGray: "#F4F4F4",
    white: "#FFFFFF",
    red: "#ef4444",
    border: "rgba(0, 0, 0, 0.05)",
  },
  fonts: {
    sans: "Inter",
    serif: "Playfair Display",
    display: "IM Fell French Canon",
    inriaSerif: "Inria Serif",
    inriaSans: "Inria Sans",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  shadows: {
    soft: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    premium: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: 0.08,
      shadowRadius: 50,
      elevation: 8,
    },
  },
};
